version: "2"
services:
  generate-vectortiles:
    environment:
      BBOX: " 116.9669,38.8867,117.7966,39.3229"
      OSM_MAX_TIMESTAMP : "2018-05-10T19:53:05Z"
      OSM_AREA_NAME: "tianjin"
      MIN_ZOOM: "0"
      MAX_ZOOM: "14"
